/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package folkvillageui;
import java.util.ArrayList;
import folkvillage.*;
import folkvillage.buildings.Building;
import java.util.Iterator;

/**
 *
 * @author sanho
 */
public class FolkVillageUI extends javax.swing.JFrame {
    
    private Village village;
    /**
     * Creates new form main
     */
    public FolkVillageUI(Village village) {
        this.village = village;
        initComponents();
        this.tick();        
    }

    private FolkVillageUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        villagewindow = new javax.swing.JPanel();
        villageLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        populationAmount = new javax.swing.JLabel();
        endTurn = new javax.swing.JButton();
        goToOther = new javax.swing.JButton();
        turnClock = new javax.swing.JLabel();
        systemExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        villageLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        villageLabel.setText("Village");

        jLabel1.setText("Population:");

        populationAmount.setText("amount");

        javax.swing.GroupLayout villagewindowLayout = new javax.swing.GroupLayout(villagewindow);
        villagewindow.setLayout(villagewindowLayout);
        villagewindowLayout.setHorizontalGroup(
            villagewindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(villagewindowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(villagewindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(villagewindowLayout.createSequentialGroup()
                        .addComponent(villageLabel)
                        .addGap(36, 36, 36))
                    .addGroup(villagewindowLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(populationAmount)))
                .addContainerGap(560, Short.MAX_VALUE))
        );
        villagewindowLayout.setVerticalGroup(
            villagewindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(villagewindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(villageLabel)
                .addGap(18, 18, 18)
                .addGroup(villagewindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(populationAmount))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        endTurn.setText("End Turn");
        endTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endTurnActionPerformed(evt);
            }
        });

        goToOther.setText("Switch View (not implemented)");
        goToOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToOtherActionPerformed(evt);
            }
        });

        turnClock.setText("Turn: 0");

        systemExit.setText("Exit");
        systemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(endTurn)
                    .addComponent(goToOther)
                    .addComponent(turnClock)
                    .addComponent(systemExit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(villagewindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {endTurn, goToOther, systemExit});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(turnClock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(goToOther, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endTurn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 555, Short.MAX_VALUE)
                .addComponent(systemExit)
                .addGap(11, 11, 11))
            .addGroup(layout.createSequentialGroup()
                .addComponent(villagewindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void initCustomComponents(){
        
    }
    private void goToOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToOtherActionPerformed
        int windowWidth = this.villagewindow.getWidth();
        int windowHeight = this.villagewindow.getHeight();
        this.villagewindow.setVisible(false);
        
    }//GEN-LAST:event_goToOtherActionPerformed

    private void systemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_systemExitActionPerformed

    private void endTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endTurnActionPerformed
        this.tick();
    }//GEN-LAST:event_endTurnActionPerformed
     
    /**
     * Tick is called after every endturn event. It calls Village's tick(),
     * which distributes the tick to all member's tick functions.
     * 
     * After tick, UI updates itself to reflect the new situation
     */
    private void tick(){
        
        this.village.tick();
        this.updateVillageScreen();
        
    }
    
    /**
     * Wraps all UI update functions
     */
    private void updateVillageScreen(){ 
        //turn counter
        this.turnClock.setText(this.village.getTurnCountAsString());
        
        //villagers
        this.populationAmount.setText( Integer.toString(this.village.getPopulation().getPopulationAmount()) );

        this.updateConstructedBuildings();
    }
    
    /**
     * Used to update all constructed buildings to UI
     */
    private void updateConstructedBuildings(){
        
        ArrayList<Building> buildings = this.village.getReadyBuildings();
        
        for (Building building : buildings) {   
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton endTurn;
    private javax.swing.JButton goToOther;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel populationAmount;
    private javax.swing.JButton systemExit;
    private javax.swing.JLabel turnClock;
    private javax.swing.JLabel villageLabel;
    private javax.swing.JPanel villagewindow;
    // End of variables declaration//GEN-END:variables
}
